### ISSUE TITLE
OLT VendorIDs

### ISSUE THREAD

**Issue by iMord0** [StephanGR/GO-BOX#1]
Add command to check VendorID of OLT with which GPON SFP communicates.
`omcicli mib get 131`
And create a table with numbers corresponding to VendorIDs.
- Default -> 128
- HWTC -> 136
- Alcatel -> 128

**Comment by StephanGR** [comment]
Yep, 

It should be a good idea, but user need to put all LEOX generated commands to be able to communicate with OLT

For example it can be : 
```bash
flash set GPON_PLOAM_PASSWD DEFAULT012
flash set OMCI_TM_OPT 0
flash set OMCI_OLT_MODE 1
flash set GPON_SN SMBXXX
flash set PON_VENDOR_ID SMBS
flash set HW_HWVER SMBSXXX
flash set OMCI_SW_VER1 SAHEXXXXXXXXX
flash set OMCI_SW_VER2 SAHEXXXXXXXXX

....Connect the fiber cable to ONT and wait a minute....
omcicli mib get 131

OltVendorId : 
```

Once user set the OltVendorID we should display the command with corresponding VendorIDs, like this :

```bash
flash set OMCC_VER 128 # If it's alactel
```

What do you think about it ?

**Comment by iMord0** [comment]
`....Connect the fiber cable to ONT and wait a minute....` - it's kinda wrong, because without cable in ONT (in this case GPON SFP = Optical Network Terminal because there optical connection ends) you can't type in commands before that. It should be something like plug into ISP Fiber box or something similar.
But the rest of your suggestion seems to be just perfect.

**Comment by StephanGR** [comment]
Hello, 

I've made a new release taking in count now the OLT Vendor ID

Program will tell user to plug cable into UDM and wait a minute
After that user will prompt the OLTVendorID and with a table value will be set according the table, if value is not present fallback to 128

Here it's how it's look like : 
```bash
===========LEOX GPON COMMAND=============
flash set GPON_PLOAM_PASSWD DEFAULT012
flash set OMCI_TM_OPT 0
flash set OMCI_OLT_MODE 1
flash set GPON_SN XXXXXXXXXXXX
flash set PON_VENDOR_ID SMBS
flash set HW_HWVER XXXXXXXXXXXX
flash set OMCI_SW_VER1 XXXXXXXXXXXXX
flash set OMCI_SW_VER2 XXXXXXXXXXXXX

## Unplug fiber from Livebox and plug it into UDM and wait a minute ##

Execute this command -> omcicli mib get 131

OLT VENDOR ID (HWTC, ALCL, ...) : alcl

Execute this command -> flash set OMCC_VER 128

=========================================
```
