### ISSUE TITLE
Livebox 6 : Unknow OLT vendor ID

### ISSUE THREAD

**Issue by faenyx** [StephanGR/GO-BOX#4]
Bonjour,

Pour la livebox 6 le vendor ID est inconnu.
En allant moi même dans l'admin je trouve dans :

Informations système > ONT > Vendor ID = SMBS

J'ai pas encore continué, il fallback pour le moment sur OMCC_VER 128.
Je croise les doigts pour que cela fonctionne.
Je vous tiens au courant de la suite.

Merci

**Comment by StephanGR** [comment]
Hello !

Si `OLT VENDOR ID` est vide, c'est que la connexion ne s'est pas faite avec l'OLT côté Orange

As-tu bien mis les informations sur le GPON ?
As-tu attendu un peu le temps que la communication se fasse ?
Le câble de fibre fonctionne-t-il bien ?
Le câble est-il branché depuis le GPON jusqu'a la prise dans ta maison/appartement et non sur la box ?

Pour info le `GPON_SN` est équivalent au numéro de série de la box

**Comment by faenyx** [comment]
Merci de la reponse rapide :p

Oui j'ai bien mis les infos sur le GPON (firmware update avec la version du tuto, aussi).
Oui j'ai meme attendu plus de 1 minute pour être bien sur, p-e pas suffisant ?
Oui il fonctionne car je récupère internet quand je le rebranche dans ma LB6.
Oui :p J'ai pas inversé a ce point là :D

Yes le GPON_SN est bon entre les informations dans l'admin de la LB6 et GO_BOX.

Voici ce que ma box dit, je sais pas si ca aide.

![image](https://github.com/StephanGR/GO-BOX/assets/14792119/248a56eb-8845-457d-b6ab-e9a40b9d328c)

**Comment by StephanGR** [comment]
Merci pour les infos !

Oui attention OLT et ONT c'est pas pareil !

ONT c'est ton Hardware -> `Terminal de Réseau Optique`
OLT c'est côté Orange la grosse armoire où sont pluggées les fibres -> `Terminal de Ligne Optique`

Tu as quel GPON de Leox ?

**Comment by StephanGR** [comment]
Top !

T'utilises quel cable de fibre ?

**Comment by faenyx** [comment]
Un cable plus grand que celui d'origine de chez que j'avais acheté ici : https://www.amazon.fr/gp/product/B07ZQGY54W/ref=ppx_yo_dt_b_search_asin_image?ie=UTF8&th=1

**Comment by StephanGR** [comment]
Les connecteurs sont de quelles couleurs ?

**Comment by faenyx** [comment]
vert et vert,

**Comment by StephanGR** [comment]
Tu as la réponse maintenant !
Il faut UPC vers APC

Bleu et Vert 

Bleu pour le GPON et Vert pour la prise

Normalement dans le lien que j'ai mis sur la doc c'est bleu et vert 

Du coup prends un cable UPC/APC et tout devrait fonctionner

**Comment by faenyx** [comment]
Et bien c'est parti, je me suis fait avoir comme un bleu, désolé du dérangement ahah,

Peut-etre que je ferais une PR pour ajouter ces informations pour les prochaines étourdis comme moi !

**Comment by StephanGR** [comment]
ahah pareil j'espère que ca va fonctionner pour toi :)

upc est coupé en biseau
apc est coupé en angle droit

Du coup ta lumière ne passe pas dans le GPON

**Comment by faenyx** [comment]
C'est donc ça ! Merci pour les explications intéressantes, je l'oublierai pas ahah :p

**Comment by StephanGR** [comment]
Ahah

J'ai failli me faire avoir aussi :)
Le câble reste le même c'est juste la prise qui change

**Comment by faenyx** [comment]
Rebondissement, je suis aller acheter ce cable (j'espère que celui ci fonctionne ?) ==> https://www.leroymerlin.fr/produits/electricite-domotique/reseau-informatique-et-telephonie/cable-ethernet-et-accessoires-informatiques/accessoires-informatiques/cable-fibre-optique-free-5m-sc-upc-lexman-82658694.html,

(J'ai aussi acheter la ref que tu as linké sur amazon, mais il arrive que dans 2 jours...)

ca ne fonctionne toujours pas, toujours pas de OltVendorId, meme après avoir attendu 5 minutes.

Par contre chose etrange, j'ai quand meme forcé OMCC_VER 128 et OMCC_VER 136, toujours pas d'ip qui apparait sur le Internet > LEOX (WAN SFP), mais ceci :

![image](https://github.com/StephanGR/GO-BOX/assets/14792119/ffa98270-75e7-4c21-929b-cfeff1551ef0)

Là je vais reset mon UDM SE pour refaire a 0.

**Comment by faenyx** [comment]
Rebondissement, je suis aller acheter ce cable (j'espère que celui ci fonctionne ?) ==> https://www.leroymerlin.fr/produits/electricite-domotique/reseau-informatique-et-telephonie/cable-ethernet-et-accessoires-informatiques/accessoires-informatiques/cable-fibre-optique-free-5m-sc-upc-lexman-82658694.html,

(J'ai aussi acheter la ref que tu as linké sur amazon, mais il arrive que dans 2 jours...)

ca ne fonctionne toujours pas, toujours pas de OltVendorId, meme après avoir attendu 5 minutes.

Par contre chose etrange, j'ai quand meme forcé OMCC_VER 128 et OMCC_VER 136, toujours pas d'ip qui apparait sur le Internet > LEOX (WAN SFP), mais ceci :

![image](https://github.com/StephanGR/GO-BOX/assets/14792119/ffa98270-75e7-4c21-929b-cfeff1551ef0)

Là je vais reset mon UDM SE pour refaire a 0.

**Comment by StephanGR** [comment]
Ca sert à rien de mettre sur le WAN tant que tu n'as pas de OLT Vendor ID

Ca veut dire que tu n'arrives pas jusqu'à chez Orange avec le cable 

Soit le câble est défectueux soit, tu n'as pas bien renseigné les valeurs dans la configuration du GPON

**Comment by faenyx** [comment]
@StephanGR Le cable Amazon recu, ca marche toujours pas, pas de OLT Vendor ID :(

Je sais plus quoi faire

Voici ce que ca donne :
Connected to 192.168.100.1.
Escape character is '^]'.


LXT-010S-H login: leox
Password:
# flash set GPON_SN SMBSXXXXXXXX
GPON_SN=SMBSXXXXXXXX
# flash set PON_VENDOR_ID SMBS
PON_VENDOR_ID=SMBS

Changement de la fibre vers le GPON... J'attends.... et ensuite ceci,

# diag gpon get onu-state
gpon get onu-state
ONU state: Operation State(O5)
RTK.0> command:# omcicli mib get 131
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
OltG
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
=================================
EntityId: 0x00
OltVendorId:
EquipId:
Version: 0
ToDInfo:
        Sequence number of GEM superframe: 0x0
        Timestamp: secs 0, nanosecs 0
=================================

**Comment by faenyx** [comment]
Ca donne ca avec l'utilitaire GO-BOX :
![image](https://github.com/StephanGR/GO-BOX/assets/14792119/cef313c3-36cf-428a-b5d4-96366a1c59dc)

**Comment by StephanGR** [comment]
Comment ca moins de variables ?

**Comment by faenyx** [comment]
La doc donne tout ca,

`flash set GPON_PLOAM_PASSWD DEFAULT012
flash set OMCI_TM_OPT 0
flash set OMCI_OLT_MODE 1
flash set GPON_SN XXXXXXXXXXXX
flash set PON_VENDOR_ID SMBS
flash set HW_HWVER XXXXXXXXXXXX
flash set OMCI_SW_VER1 XXXXXXXXXXXXX
flash set OMCI_SW_VER2 XXXXXXXXXXXXX`

**Comment by StephanGR** [comment]
ajoutes moi sur discord : stoufiler

**Comment by faenyx** [comment]
In fine, missing `flash set HW_HWVER XXXXXXX` ,

Thanks @StephanGR
